### ISSUE TITLE
use of --submit flag in cli (file_run) yields error

### ISSUE THREAD

**Issue by matthigger** [matthigger/gradescope_auto_py#13]
observed in ds2500 hw7

**Comment by matthigger** [comment]
```
[NbConvertApp] Converting notebook hw7_rub.ipynb to script
[NbConvertApp] Writing 15227 bytes to hw7_rub.py
/home/matt/.local/lib/python3.10/site-packages/gradescope_auto_py/gradescope/build_auto.py:56: UserWarning: removing zip file from include: /tmp/tmpgjbace4x/include/hw7_rub.zip
  warn(f'removing zip file from include: {file_zip}')
INFO: Successfully saved requirements file in /tmp/tmpgjbace4x/requirements.txt
finished building: /home/matt/Dropbox/teach/DS2500/hw/hw7/autograde/hw7_rub.zip
when uploading zip, be sure to set autograder points to: 14.0
(inconsistent values cause "expect not formatted correctly")
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/matt/.local/lib/python3.10/site-packages/gradescope_auto_py/__main__.py", line 59, in <module>
    main(args)
  File "/home/matt/.local/lib/python3.10/site-packages/gradescope_auto_py/__main__.py", line 50, in main
    grader.grade(args.f_submit)
  File "/home/matt/.local/lib/python3.10/site-packages/gradescope_auto_py/grader.py", line 47, in grade
    s_file_prep, token = self.prep_file(file=file_run,
  File "/home/matt/.local/lib/python3.10/site-packages/gradescope_auto_py/grader.py", line 177, in prep_file
    with open(file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpv2ddorkx/hw7.py'
```

**Comment by matthigger** [comment]
replaced with 

```
$ python3 -m gradescope_auto_py.grade -z auto.zip -s hw0.py
```

tested in 0.0.18
